repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/semgrep/pre-commit
    rev: v1.147.0
    hooks:
      - id: semgrep
        pass_filenames: false
        args:
          - "--config"
          - "auto"
          - "-j"
          - "1"