FROM node:20-alpine AS build

WORKDIR /app

COPY client/package*.json ./

RUN npm ci

COPY client/ ./

ARG REACT_APP_API_URL
ARG REACT_APP_ENV

ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_ENV=$REACT_APP_ENV

RUN npm run build


FROM nginxinc/nginx-unprivileged:alpine

USER root
RUN apk upgrade --no-cache
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

USER 101
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
